### ISSUE TITLE
ImportError: cannot import name fields

### ISSUE THREAD

**Issue by macmanes** [MG-RAST/MG-RAST-Tools#129]
Cloned repo this AM

`/share/MG-RAST-Tools/tools/bin/mg-download.py --metagenome mgm4440442.4 --dir .`

error

```
Traceback (most recent call last):
  File "/share/MG-RAST-Tools/tools/bin/mg-download.py", line 7, in <module>
    from mglib import *
  File "/share/MG-RAST-Tools/tools/lib/mglib.py", line 13, in <module>
    from requests_toolbelt import MultipartEncoder
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/__init__.py", line 14, in <module>
    from .multipart import (
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/multipart/__init__.py", line 11, in <module>
    from .encoder import MultipartEncoder, MultipartEncoderMonitor
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/multipart/encoder.py", line 12, in <module>
    from urllib3.poolmanager import fields
ImportError: cannot import name fields
```

```
python --version
Python 2.7.6
```

Please advise.

**Comment by jaredbischof** [comment]
Hi there, did you try this:

"In order for some scripts to run properly you have to add the lib directory to your PYTHONPATH and PERL5LIB. Please add the lib directory to your PYTHONPATH and PERL5LIB, or source the set_env.sh script inside this directory."

**Comment by wltrimbl** [comment]
Try:
`python -c 'import requests; print requests.__version__' ` 
If the version reported is less than 2.5.1, this error is caused by requests being too old.

I was able to remedy this by using 
`pip install requests --upgrade`
